name: rtmp_publisher_example
description: Demonstrates how to use the rtmp_publisher plugin.

publish_to: 'none'

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  rtmp_publisher:
    path: ../

  path_provider: ^1.6.8
  cupertino_icons: ^0.1.3
  video_player: ^0.10.11
  e2e: ^0.4.2
  wakelock: ^0.1.4+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0

flutter:
  uses-material-design: true