name: rtmp_broadcaster_example
description: Demonstrates how to use the rtmp_broadcaster plugin.

publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  rtmp_broadcaster:
    path: ../

  path_provider: ^2.0.15
  cupertino_icons: ^1.0.5
  video_player: ^2.7.0
  wakelock_plus: ^1.2.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
